### ISSUE TITLE
Ha dejado de actualizar

### ISSUE THREAD

**Issue by emrivero** [ccamara/covid_spain#4]
Parece que la aplicación ha dejado de actualizar los datos. He visto que en https://github.com/datadista/datasets/tree/master/COVID%2019 hay datos hasta el 16 de Abril.

En la aplicación los datos solo llegan hasta el día 13.

**Comment by ccamara** [comment]
Gracias por avisar. Acabo de subir los datos actualizados. Celebro que sean de interés para alguien.
